### PR TITLE
Camera-ready version of schneider2021re

### PR DESCRIPTION
**Pull request by M-Koerner**
Dear all,

we also made our first steps. The document compiles flawlessly. 

Our report summary extends over the first page. Should we leave the page break or can we rather start with the main content right away?

Best regards!

### CODE REVIEW

**Comment by M-Koerner** [comment]
BTW: We added some relative symlinks across directories to make everything work without creating deep copies of files. Hope that's fine.

**Comment by koustuvsinha** [comment]
LGTM! Yes, a page break is fine after the summary. And relative symlinks is also fine, compilation works on my end! Thanks :) 

@dodgejesse can you review the contents of the paper in this PR? Thanks!

**Review by dodgejesse — CHANGES_REQUESTED** [review]
Please include the article.pdf file so we can review it.

**Comment by M-Koerner** [comment]
Hi Jesse!
I've added the compiled pdf
Best, Marco

**Comment by dodgejesse** [comment]
Looks good to me! Nice work.

**Pull request merged**
