### PR TITLE
EmbedKGQA files

### PR DESCRIPTION
**Pull request by jishnujayakumar**
- Following things are not working properly
  - Bibliography 
  - Label and references 
  - Latex's ```\newcommand```

### CODE REVIEW

**Comment by koustuvsinha** [comment]
Hi, please clean the conflicts in this PR for us to be able to review. Specifically, make sure the changes in your commit are only confined within your assigned folder. Thanks!

**Comment by jishnujayakumar** [comment]
> Hi, please clean the conflicts in this PR for us to be able to review. Specifically, make sure the changes in your commit are only confined within your assigned folder. Thanks!

@koustuvsinha, I have rectified the conflicts.

**Comment by koustuvsinha** [comment]
Please change the following:

1. Remove `\usepackage[T1]{fontenc}` from packages.tex
2. In content.tex Line 41, from the table caption, remove `\centering` and `\newline`
3. In your bibliography.bib, there is an error in `yago` bibtex, where the abstract contains a runaway %  (Our empirical evaluation of fact correctness shows an accuracy of about 95%) --> add an escape sequence before %, or better scrap the abstract. 

```
@inproceedings{yago,
author = {Suchanek, Fabian M. and Kasneci, Gjergji and Weikum, Gerhard},
title = {Yago: A Core of Semantic Knowledge},
year = {2007},
isbn = {9781595936547},
publisher = {Association for Computing Machinery},
address = {New York, NY, USA},
url = {https://doi.org/10.1145/1242572.1242667},
doi = {10.1145/1242572.1242667},
abstract = {We present YAGO, a light-weight and extensible ontology with high coverage and quality. YAGO builds on entities and relations and currently contains more than 1 million entities and 5 million facts. This includes the Is-A hierarchy as well as non-taxonomic relations between entities (such as HASONEPRIZE). The facts have been automatically extracted from Wikipedia and unified with WordNet, using a carefully designed combination of rule-based and heuristic methods described in this paper. The resulting knowledge base is a major step beyond WordNet: in quality by adding knowledge about individuals like persons, organizations, products, etc. with their semantic relationships - and in quantity by increasing the number of facts by more than an order of magnitude. Our empirical evaluation of fact correctness shows an accuracy of about 95\%. YAGO is based on a logically clean model, which is decidable, extensible, and compatible with RDFS. Finally, we show how YAGO can be further extended by state-of-the-art information extraction techniques.},
booktitle = {Proceedings of the 16th International Conference on World Wide Web},
pages = {697–706},
numpages = {10},
keywords = {WordNet, wikipedia},
location = {Banff, Alberta, Canada},
series = {WWW '07}
}
```

4. Please fix the width of Tables 3 and 9, they are overflowing their margins

**Comment by jishnujayakumar** [comment]
Hi @koustuvsinha, I have rectified the latex compilation error. Kindly have a look.

**Comment by koustuvsinha** [comment]
Looks good to me!

**Comment by koustuvsinha** [comment]
Although, your PR still contains tons of conflicts. Can you revert any changes you have made in another folders? @jishnujayakumar

**Comment by koustuvsinha** [comment]
Hi @jishnujayakumar, thanks for the commit but unfortunately there is a lot more conflicts in the branch. Attaching screenshot of the same. Please fix these at the earliest.

Make sure that your commit _only_ changes files from your folder.

Screen Shot 2021-05-23 at 12 11 02 AM

**Comment by jishnujayakumar** [comment]
> Hi @jishnujayakumar, thanks for the commit but unfortunately there is a lot more conflicts in the branch. Attaching screenshot of the same. Please fix these at the earliest.
> 
> Make sure that your commit _only_ changes files from your folder.
> 
> Screen Shot 2021-05-23 at 12 11 02 AM

Hi @koustuvsinha, I have tried to fix the conflicts. Kindly check.

**Comment by koustuvsinha** [comment]
Your commits still change way too many files outside of your folder (attached). I guess you attempted a rebase and then pushed the files. Unfortunately it is risky as I cannot review all those changes. I would suggest you to close this PR, and open a new PR (with a new fork of this repository) with your files. (backup your work before deleting your fork) 

Again, your PR should only affect the files in your folder!

Screen Shot 2021-05-23 at 12 54 06 AM

**Comment by jishnujayakumar** [comment]
> Your commits still change way too many files outside of your folder (attached). I guess you attempted a rebase and then pushed the files. Unfortunately it is risky as I cannot review all those changes. I would suggest you to close this PR, and open a new PR (with a new fork of this repository) with your files. (backup your work before deleting your fork)
> 
> Again, your PR should only affect the files in your folder!
> 
> Screen Shot 2021-05-23 at 12 54 06 AM

Ok, I understand. I will follow your suggestion.

**Pull request closed without merging**
