### PR TITLE
First Version of camera ready version for harrison2021learning

### PR DESCRIPTION
**Pull request by RedHilarious**
Hey,

so this is the first version of our camera-ready paper. There are still quite some open issues we are aware of, but as mentioned in the last email we wanted to submit the PR as early as possible so that you can comment on our compile issues. 

The main issues we still have are:

- Bibliography not compiled into the `article.pdf`
- Visual appearance with the read header and also the editor section on the first side of the `article.pdf` are messed up
- Tables too wide (we are aware and will fix this; e.g. split into 2 parts)

I will open an issue linking to our PR, and the logs attached.

Thanks!

### CODE REVIEW

**Comment by koustuvsinha** [comment]
Hi @RedHilarious, I think I narrowed down the compilation issue to two things:

1. Latex is breaking on the table `tab:computation-table` on L150 in your openreview/content.tex (https://github.com/RedHilarious/RC-2020/blob/main/harrison2021learning/openreview/content.tex#L150-L176)
Please check this table - probably there should be a separator between the multicolumns? The compilation works on removing this table.

2. In L95 (https://github.com/RedHilarious/RC-2020/blob/main/harrison2021learning/openreview/content.tex#L95), a `citep` is misplaced with unknown commmand `sqcitep`

**Comment by RedHilarious** [comment]
Hey @koustuvsinha, thanks for your feedback! Indeed these two things fixed our issues. We have also fixed the table widths now so they match the text width.

One more question. We used `citet` and `citep` in our original latex code, but I feel this does not work the same anymore in this template. I tried two things:

- use the package `\usepackage[round]{natbib}` in my `packages.tex` lead to this compilation error log: [make-natbib.out](https://pastebin.com/nKYkij8E)
- use the lines `\bibliography{bibliography} \bibliographystyle{bibstyle}` in the `article.tex` lead to this compilation error log: [make-bibstyle.out](https://pastebin.com/3UrrQrCR)

Do you have an idea how I can use the bibstyle / natbib packages? Should I open another issue for this?

**Comment by koustuvsinha** [comment]
Hi @RedHilarious, I believe it's just a convention in ReScience style files, they do work as intended: the `citet` is displayed as `Author^{num}` and `citep` / `cite` is displayed as `[num]`. I checked and the compilation works on my end, thanks!

**Comment by koustuvsinha** [comment]
@sashavor can you review the contents of the article? Looks good to me on my end

**Review by sashavor — COMMENTED** [review]
The pdf looks good!
@RedHilarious, can you please remove the page break between the 'Communication with Original Authors' and the intro?

**Comment by RedHilarious** [comment]
@sashavor I removed the page break, please review again.

**Pull request merged**
