### PR TITLE
First version of camera-ready version for li2021reimplementation

### PR DESCRIPTION
**Pull request by Huihhh**

### CODE REVIEW

**Comment by koustuvsinha** [comment]
The compilation breaks here: please fix the file name

```
! LaTeX Error: File `../openreview/related work.tex' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: tex)

Enter file name: 
! Emergency stop.
<read *> 
         
l.11 \input{../openreview/related work.tex}
```

**Comment by Huihhh** [comment]
Fix file name: space removed.
"../openreview/related work.tex" works well on our local machines. Since 'intro.tex', which is loaded before 'related work.tex', can be found, we assume it is caused by the space.

**Comment by koustuvsinha** [comment]
LGTM! @jzf2101 can you review the contents of the paper? Thanks!

**Comment by koustuvsinha** [comment]
Self assigned to review due to no reply from @jzf2101. Looks good to me content-wise.

**Pull request merged**
