### PR TITLE
camera ready version

### PR DESCRIPTION
**Pull request by tzole1155**
Hi , this is a complied version of our camera ready paper.

If there are any issue regarding the latex code please let us know.

Thanks,
Giorgos

PS: Due to a bug related to the titlesec package and the numbering of Sections I've included some additional [code](https://github.com/tzole1155/RC-2020/blob/main/albanis2021on/openreview/packages.tex#L28-L32).
Hope that this ok.

### CODE REVIEW

**Comment by koustuvsinha** [comment]
Please add a "[Re]" suffix in the title. Compilation works on my end.

**Comment by tzole1155** [comment]
Hi,

I have updated the title.

Best,

Giorgos

**Comment by koustuvsinha** [comment]
Thanks for the update! Looks good to me now!

@jzf2101 Can you review the content of the pdf once? Compilation works on my end.

**Review by jzf2101 — APPROVED** [review]
Based on the pre-compiled pdf, the results look similar to that presented in the original submission. LGTM.

**Pull request merged**
